spring.application.name=BlogSphere

spring.datasource.url=jbdc:mysql://localhost:3306/blogshere
spring.datasource.username=username
spring.datasource.password=password 
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update