spring.application.name=BlogSphere

spring.datasource.url=jbdc:mysql://localhost:3306/blogshere
spring.datasource.username=root
spring.datasource.password=Mtklsduftuv972@ 

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
backend.app.jwtSecret=MMstfkalM6521@azertyuiopsdfghjklmxcvbnfyebieiubi
backend.app.jwtExpirationMs=60000000
backend.app.jwtRefreshExpirationMs=2629800000
spring.jpa.defer-datasource-initialization: true
