spring.application.name=BlogSphere

spring.datasource.url=jbdc:postgresql://dpg-cs80s688fa8c73biegn0-a:5432/blogshere
spring.datasource.username=root
spring.datasource.password=root@ 

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
backend.app.jwtSecret=MMstfkalM6521@azertyuiopsdfghjklmxcvbnfyebieiubi
backend.app.jwtExpirationMs=60000000
backend.app.jwtRefreshExpirationMs=2629800000
spring.jpa.defer-datasource-initialization: true
